### ISSUE TITLE
Request: To add more holiday icons

### ISSUE THREAD

**Issue by adithyakhamithkar** [fravaccaro/harbour-dyncal#1]
Hi,

Thank you very much for creating this app. I really like it. I would like to request you to please add more holiday icons for all those people in different regions where sailfish is popular. If you can make the app to get the icons from an API it would be really nice so that we can update holidays and icons in a portal and get them to sync on the phone.

**Comment by fravaccaro** [comment]
Hi!

Thank you so much for your kind words. I was actually investigating a way to add this :)

Mine is not a proper app, just a simple bash script, so no API is possible, but I'm planning to give proper documentation on how to build "extensions" and hook to my script. 

Stay tuned :)

**Comment by adithyakhamithkar** [comment]
That would be great I'll keep a watch and wait for it.

**Comment by fravaccaro** [comment]
Released https://github.com/fravaccaro/harbour-dyncal/wiki/Extensions
I hope it's what you asked for :)
I tried to be as clear as possible in the wiki.

**Comment by adithyakhamithkar** [comment]
Thanks I'll give it a try. I will have to brush up my design skill :)
